use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => true

target 'HelloWorld' do
  platform :osx, '10.10'
  pod 'Criollo', :git => '../../', :submodules => true
  pod 'CSSystemInfoHelper', '~> 1.4'
end

target 'HelloWorld-Cocoa' do
  platform :osx, '10.10'
  pod 'Criollo', :git => '../../', :submodules => true
  pod 'CSSystemInfoHelper', '~> 1.4'
end

target 'HelloWorld-iOS' do
  platform :ios, '8.0'
  pod 'Criollo', :git => '../../', :submodules => true
  pod 'CSSystemInfoHelper', '~> 1.4'
end

target 'HelloWorld-tvOS' do
  platform :tvos, '9.0'
  pod 'Criollo', :git => '../../', :submodules => true
  pod 'CSSystemInfoHelper', '~> 1.4'
end
