use_frameworks!

target 'HelloWorld' do
  platform :osx, '10.10'
  pod 'Criollo', :path => '../../'
  pod 'CSSystemInfoHelper', '~> 1.4'
end

target 'HelloWorld-Cocoa' do
  platform :osx, '10.10'
  pod 'Criollo', :path => '../../'
  pod 'CSSystemInfoHelper', '~> 1.4'
end

target 'HelloWorld-iOS' do
  platform :ios, '8.0'
  pod 'Criollo', :path => '../../'
  pod 'CSSystemInfoHelper', '~> 1.4'
end
