use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => true

target 'SecureHTTPServer' do
  platform :ios, '12.0'
  pod 'Criollo', :git => '../../', :submodules => true
  pod 'CSSystemInfoHelper', '~> 1.4'
end
