require_relative '../Podfile.common.rb'

use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => $generate_multiple_pod_projects

target 'LongRequest' do
  platform :osx, $osx_platform
  pod 'Criollo', :git => $repo, :submodules => true
end

tweaks
