platform :osx, '10.10'
use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => true

target 'HelloWorld-Swift' do
  pod 'Criollo', :git => '../../', :submodules => true
  pod 'CSSystemInfoHelper', '~> 1.4'
end

