require_relative '../Podfile.common.rb'

use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => $generate_multiple_pod_projects

target 'HelloWorld-Swift' do
  platform :osx, $osx_platform
  pod 'Criollo', :git => $repo, :submodules => true
  
  pod 'CSSystemInfoHelper', '~> 1.4'
end

tweaks
